name: Test notebooks

on:
    push:
        branches:
            - main
            # - master

    pull_request:
        branches:
            - main
            # - master

    workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64] 
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      # Commented out since lab notebooks aren't packages to be built
      #- name: Build Package
      #- uses: julia-actions/julia-buildpkg@v1

      - name: Run Tests
        uses: julia-actions/julia-runtest@v1
